# Generated by Django 4.2.27 on 2026-02-21 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='profile picture')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('pricing_sheet', models.CharField(blank=True, default='', max_length=128)),
                ('wwt_region', models.CharField(choices=[('NAIC', 'NAIC'), ('EIC', 'EIC'), ('AIC-S', 'AIC-S'), ('UNKNOWN', 'UNKNOWN')], default='NAIC', max_length=16)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterSKUMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_sku_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_type', models.CharField(choices=[('Primary', 'Primary'), ('Additional', 'Additional')], default='Primary', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_sku_mappings',
            },
        ),
        migrations.CreateModel(
            name='PartnerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_sku_name', models.CharField(blank=True, max_length=255, null=True)),
                ('master2_price_list', models.CharField(blank=True, max_length=255, null=True)),
                ('master3_first_call', models.CharField(blank=True, max_length=255, null=True)),
                ('master3_breakfix_4hr', models.CharField(blank=True, max_length=255, null=True)),
                ('master3_breakfix_nbd', models.CharField(blank=True, max_length=255, null=True)),
                ('master4_deploy_per_install', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partner_mappings',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(blank=True, max_length=128)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('work_order_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(choices=[('Public', 'Public'), ('Commercial', 'Commercial')], default='Public Sector', max_length=64)),
                ('term', models.CharField(choices=[('60', '60'), ('45', '45'), ('30', '30')], default='60', max_length=64)),
                ('support', models.CharField(choices=[('4hr', '4hr'), ('NBD', 'NBD')], default='4 hrs', max_length=64)),
                ('google_legal_entity', models.CharField(blank=True, max_length=255)),
                ('google_bill_to_address', models.TextField(blank=True)),
                ('google_ship_to_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPrimarySKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_primary_items', to='users.masterskumapping')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_sku_items', to='users.workorder')),
            ],
            options={
                'verbose_name': 'WorkOrder Primary SKU',
                'verbose_name_plural': 'WorkOrder Primary SKUs',
                'db_table': 'workorder_primary_skus',
                'unique_together': {('workorder', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAdditionalSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_additional_items', to='users.masterskumapping')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_sku_items', to='users.workorder')),
            ],
            options={
                'verbose_name': 'WorkOrder Additional SKU',
                'verbose_name_plural': 'WorkOrder Additional SKUs',
                'db_table': 'workorder_additional_skus',
                'unique_together': {('workorder', 'sku')},
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='additional_skus',
            field=models.ManyToManyField(blank=True, limit_choices_to={'sku_type': 'Additional'}, related_name='workorders_additional_skus', through='users.WorkOrderAdditionalSKU', to='users.masterskumapping'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='country',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.PROTECT, to='users.country'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='primary_skus',
            field=models.ManyToManyField(blank=True, limit_choices_to={'sku_type': 'Primary'}, related_name='workorders_primary_skus', through='users.WorkOrderPrimarySKU', to='users.masterskumapping'),
        ),
        migrations.AddField(
            model_name='masterskumapping',
            name='partner_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_mappings', to='users.partnermapping'),
        ),
        migrations.AddField(
            model_name='country',
            name='additional_skus',
            field=models.ManyToManyField(blank=True, limit_choices_to={'sku_type': 'Additional'}, related_name='additional_skus', to='users.masterskumapping'),
        ),
        migrations.AddField(
            model_name='country',
            name='primary_skus',
            field=models.ManyToManyField(blank=True, limit_choices_to={'sku_type': 'Primary'}, related_name='primary_skus', to='users.masterskumapping'),
        ),
    ]
