# Generated by Django 4.2.27 on 2026-02-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_polulate_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterskumapping',
            name='quantity',
        ),
    ]
