# Generated by Django 4.2.27 on 2026-02-27 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_masterskumapping_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='sector',
            field=models.CharField(choices=[('Public', 'Public Sector'), ('Commercial', 'Commercial Sector')], default='Public Sector', max_length=64),
        ),
        migrations.CreateModel(
            name='WorkOrderPriceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_estimates', to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_estimates', to='users.workorder')),
            ],
            options={
                'verbose_name': 'Work Order Price Estimate',
                'verbose_name_plural': 'Work Order Price Estimates',
                'db_table': 'workorder_price_estimates',
                'ordering': ['-generated_at'],
            },
        ),
    ]
